runtime: nodejs20

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /styles.css
  static_files: public/styles.css
  upload: public/styles.css

- url: /styles2.css
  static_files: public/styles2.css
  upload: public/styles2.css

- url: /images/(.*)
  static_files: public/images/\1
  upload: public/images/(.*)

- url: /(.*\.html)
  static_files: public/\1
  upload: public/(.*\.html)

env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/st-supps:us-east4:stsupps
  DB_USER: souderst
  DB_PASS: password
  DB_NAME: ST-Supps
